version: '2.2'
services:
  tarefax-postgres:
    extends:
      file: postgres/postgres.yml
      service: postgres
    container_name: tarefax-postgres
  tarefax-elasticsearch:
    extends:
      file: elasticsearch/elasticsearch.yml
      service: elasticsearch
    container_name: tarefax-elasticsearch
  tarefax-jhipster-registry:
    extends:
      file: jhipster-registry/jhipster-registry.yml
      service: jhipster-registry
    container_name: tarefax-jhipster-registry
  redis-gprepfter:
    extends:
      file: redis/redis.yml
      service: redis
    container_name: tarefax-redis
