version: '2'
services:
  minio:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z-37-ged264449b
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    command: server /data
    ports:
      - "9000:9000"
